### ISSUE TITLE
Issue about gamma initialization

### ISSUE THREAD

**Issue by JianJuly** [gmum/Kernel_SA-AbMILP#1]
Thanks you for sharing this code, it helps me a lot. 
I found some  issues concerning the parameter initialization.
In the model.py, Line 86 `self.gamma = nn.Parameter((torch.ones(1)).cuda())`, the gamma is initialized to be 1
Yet it reads in the paper,  ‘γ is a trainable scalar initialized to 0’. 
Though it can make little difference, i am still wondering if i had any misunderstanding on it?

**Comment by dawrym** [comment]
Thanks for reporting that, I've already fixed it. You are right, it should be zeros ;)
