### ISSUE TITLE
Access to the datasets

### ISSUE THREAD

**Issue by WeijiaZhang24** [gmum/Kernel_SA-AbMILP#3]
Hi,

Thanks so much for sharing this code. I wonder if it is possible to also share the pre-processed patches of the histopathology datasets? 

I am very interested in these tasks, but do not have any histopathology knowledge coming from a machine learning background. 

Thanks!

**Comment by dawrym** [comment]
Hello, 

Unfortunately, we do not have preprocessed patches anymore. They cannot be shared. 

Best regards, 
Dawid
