### ISSUE TITLE
About Breast Data Preprocessing

### ISSUE THREAD

**Issue by CongDo0820** [gmum/Kernel_SA-AbMILP#4]
Hi, thank you for sharing the code. I'm trying to use your code for my image data, I'm a newbie in PyTorch and I want to ask about the train-test split step. In detail, in breast_loader.py, Line 50-51, how can we get the 'train_val_idxs' and 'tests_idxs' ? Sorry if I've asked a dummy question.

**Comment by dawrym** [comment]
Hi,

They are randomly generated and saved into a file with sklearn with https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.StratifiedShuffleSplit.html 
The splits are stratified and organized into folds and repeated 5 times.
